### ISSUE TITLE
Create Individual Socrata pages for Zoning Features

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/product-metadata#12]
DCP publishes [Zoning GIS Data: Shapefile](https://data.cityofnewyork.us/City-Government/Zoning-GIS-Data-Shapefile/kdig-pewd) and [Zoning GIS Data: Geodatabase](https://data.cityofnewyork.us/City-Government/Zoning-GIS-Data-Geodatabase/mm69-vrje/about_data) to the [NYC Open Data portal](https://opendata.cityofnewyork.us/data/). 

The shapefile page consists of several shapefiles grouped together, in the old Socrata format. We need to break up the group page and create new, individual Socrata pages for each Zoning feature:

- [ ] Commercial Overlay Districts
- [ ]  Limited Height Districts
- [ ] Special Purpose Districts
- [ ] Special Purpose Districts with Subdistricts
- [ ] Zoning Districts
- [ ] Zoning Map Amendments

We may also want to remove the Zoning GIS Data: Geodatabase version from the portal.

**Comment by alexrichey** [comment]
Had duplicated this in our current sprint, [here](https://github.com/orgs/NYCPlanning/projects/27/views/18?pane=issue&itemId=79142084). Finished it up, and noted the new four-fours for each dataset. At the end of the sprint, I'll go through and catalog all the new four-fours that need internal approval, then submission to OTI to migrate.
